apiVersion: v1
kind: Service
metadata:
  name: better-backend-app-service
  namespace: default
spec:
  selector:
    app: better-backend-app  # Match the pod label of your application
  ports:
    - protocol: TCP
      port: 80           # Your service port
      targetPort: 8000    # Your pod container port
  type: LoadBalancer
  loadBalancerIP: "better-staging-static-ip"  # The static IP you created in GCP
